# Dockerfile 

# Use the official Ubuntu 20.04 base image
FROM ubuntu:20.04 

# Update package list and install SBCL (Steel Bank Common Lisp)
RUN apt update && apt install -y sbcl 


# Set the working directory
WORKDIR /usr/src